=== SpeckiJ/thesis/framework/orchestrator/src/main/resources/static/configSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://specki.xyz/intueri/configSchema.json",
  "type": "object",
  "title": "Schema describing the json representation of the config for an intueri-detector",
  "required": [
    "connector.class",
    "offset.storage",
    "offset.storage.file.filename",
    "offset.flush.interval.ms",
    "name",
    "database.hostname",
    "database.port",
    "database.user",
    "database.password",
    "database.dbname",
    "server.id",
    "database.server.name",
    "database.history",
    "database.history.file.filename",
    "table.blacklist",
    "engine.threads.corePoolSize",
    "engine.threads.maxPoolSize"
  ],
  "properties": {
    "id": {
      "type": "string",
      "title": "Unique Identifier of this Configuration. This value is autogenerated by the Server if not set.",
      "example": "9c90817d-a107-4a78-ab71-1057301e2fb9"
    },
    "name": {
      "type": "string",
      "title": "Human readable name of this Configuration",
      "example": "Configuration for Primary Datastore XY123"
    },
    "connector.class": {
      "type": "string",
      "title": "The Connector.class Schema",
      "default": "",
      "example": "io.debezium.connector.postgresql.PostgresConnector",
      "pattern": "^(.*)$"
    },
    "offset.storage": {
      "type": "string",
      "title": "The Offset.storage Schema",
      "default": "",
      "example": "org.apache.kafka.connect.storage.FileOffsetBackingStore",
      "pattern": "^(.*)$"
    },
    "offset.storage.file.filename": {
      "type": "string",
      "title": "The Offset.storage.file.filename Schema",
      "default": "",
      "example": "offset.dat",
      "pattern": "^(.*)$"
    },
    "offset.flush.interval.ms": {
      "type": "integer",
      "title": "The Offset.flush.interval.ms Schema",
      "default": 0,
      "example": 60000
    },
    "database.hostname": {
      "type": "string",
      "title": "The Database.hostname Schema",
      "default": "",
      "example": "127.0.0.1",
      "pattern": "^(.*)$"
    },
    "database.port": {
      "type": "integer",
      "title": "The Database.port Schema",
      "default": 0,
      "example": 5000
    },
    "database.user": {
      "type": "string",
      "title": "The Database.user Schema",
      "default": "",
      "example": "postgres",
      "pattern": "^(.*)$"
    },
    "database.password": {
      "type": "string",
      "title": "The Database.password Schema",
      "default": "",
      "example": "postgres",
      "pattern": "^(.*)$"
    },
    "database.dbname": {
      "type": "string",
      "title": "The Database.dbname Schema",
      "default": "",
      "example": [
        "test"
      ],
      "pattern": "^(.*)$"
    },
    "server.id": {
      "type": "integer",
      "title": "The Server.id Schema",
      "default": 0,
      "example": 85744
    },
    "database.server.name": {
      "type": "string",
      "title": "The Database.server.name Schema",
      "default": "",
      "example": "test",
      "pattern": "^(.*)$"
    },
    "database.history": {
      "type": "string",
      "title": "The Database.history Schema",
      "default": "",
      "example": "io.debezium.relational.history.FileDatabaseHistory",
      "pattern": "^(.*)$"
    },
    "database.history.file.filename": {
      "type": "string",
      "title": "The Database.history.file.filename Schema",
      "default": "",
      "example": "dbhistory.dat",
      "pattern": "^(.*)$"
    },
    "table.blacklist": {
      "type": "string",
      "title": "The Table.blacklist Schema",
      "default": "",
      "example": "public.spatial_ref_sys",
      "pattern": "^(.*)$"
    },
    "engine.threads.corePoolSize": {
      "type": "integer",
      "title": "The Engine.threads.corepoolsize Schema",
      "default": 0,
      "example": 4
    },
    "engine.threads.maxPoolSize": {
      "type": "integer",
      "title": "The Engine.threads.maxpoolsize Schema",
      "default": 1,
      "example": 4
    }
  }
}

=== SpeckiJ/thesis/framework/orchestrator/detectorConfigExample.json
{
  "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
  "offset.storage": "org.apache.kafka.connect.storage.FileOffsetBackingStore",
  "offset.storage.file.filename": "offset.dat",
  "offset.flush.interval.ms": 60000,
  "name": "postgres-connector",
  "database.hostname": "127.0.0.1",
  "database.port": 5000,
  "database.user": "postgres",
  "database.password": "",
  "database.dbname": "test",
  "server.id": 85744,
  "database.server.name": "test",
  "database.history": "io.debezium.relational.history.FileDatabaseHistory",
  "database.history.file.filename": "dbhistory.dat",
  "table.blacklist": "public.spatial_ref_sys",
  "engine.threads.corePoolSize": 4,
  "engine.threads.maxPoolSize": 4
}
